In [2]:
import numpy as np


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.random.randint(10)

4

In [10]:
np.random.randn(19)

array([ 2.19337611, -0.62603656, -0.8193054 ,  0.30990545, -0.05993307,
        1.15810739, -0.85326239,  0.21377846, -1.17776523, -0.38361847,
       -1.47779476, -0.79440784,  0.18755882, -1.27221342, -0.65397306,
       -0.07219525,  1.53801865, -0.37074335, -1.15702719])

In [17]:
np.array([[1,2,3],[4,5,6]]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.random.uniform(10,40,size=(4,5))

array([[20.15277509, 15.42032979, 36.36651056, 33.15152837, 18.17955638],
       [27.78576869, 34.26420898, 32.24192165, 11.28428475, 17.52206878],
       [27.680454  , 25.05350306, 27.53849117, 14.83373488, 18.00735822],
       [21.18414094, 35.74414636, 13.40549814, 17.80020592, 37.17584694]])

In [23]:
k=np.array([[1,2,3],[4,5,6]])

In [30]:
k

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
k[1,2]

6

In [34]:
k[1:]

array([[4, 5, 6]])

In [35]:
k[0:,1:]

array([[2, 3],
       [5, 6]])

In [42]:
k[1::1]

array([[4, 5, 6]])

In [43]:
k.flatten()

array([1, 2, 3, 4, 5, 6])

In [50]:
m=np.random.randint(100,200,size=(10,10))
m

array([[162, 139, 103, 110, 170, 131, 131, 189, 141, 125],
       [126, 120, 162, 142, 144, 165, 135, 115, 142, 106],
       [122, 157, 104, 122, 135, 125, 110, 132, 114, 161],
       [198, 140, 149, 166, 186, 120, 129, 118, 198, 129],
       [159, 193, 187, 178, 126, 184, 187, 111, 157, 150],
       [192, 101, 104, 161, 161, 180, 154, 137, 126, 194],
       [190, 150, 194, 101, 111, 197, 101, 141, 124, 153],
       [168, 102, 105, 175, 186, 112, 145, 103, 167, 102],
       [117, 140, 181, 123, 162, 158, 151, 160, 100, 141],
       [185, 197, 112, 194, 172, 156, 156, 146, 175, 121]])

In [51]:
np.sort(m,axis=0)

array([[117, 101, 103, 101, 111, 112, 101, 103, 100, 102],
       [122, 102, 104, 110, 126, 120, 110, 111, 114, 106],
       [126, 120, 104, 122, 135, 125, 129, 115, 124, 121],
       [159, 139, 105, 123, 144, 131, 131, 118, 126, 125],
       [162, 140, 112, 142, 161, 156, 135, 132, 141, 129],
       [168, 140, 149, 161, 162, 158, 145, 137, 142, 141],
       [185, 150, 162, 166, 170, 165, 151, 141, 157, 150],
       [190, 157, 181, 175, 172, 180, 154, 146, 167, 153],
       [192, 193, 187, 178, 186, 184, 156, 160, 175, 161],
       [198, 197, 194, 194, 186, 197, 187, 189, 198, 194]])

In [60]:
p=np.arange(1,101).reshape(10,10)

In [61]:
np.where(p>50,p/10,p)

array([[ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ],
       [11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. , 20. ],
       [21. , 22. , 23. , 24. , 25. , 26. , 27. , 28. , 29. , 30. ],
       [31. , 32. , 33. , 34. , 35. , 36. , 37. , 38. , 39. , 40. ],
       [41. , 42. , 43. , 44. , 45. , 46. , 47. , 48. , 49. , 50. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

### shape and reshape

In [47]:
k=list(map(int, input().split()))
print(np.array(k).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Polynomials

In [1]:
import numpy as np
np.polyval([1,2,3,4],3)

58

In [5]:
arr = list(map(int, input().split()))
n=int(input())
np.polyval(arr,n)

1 2
3


5

### Concatenate

In [4]:
import numpy as np
arr1=[]
arr2=[]
n,m,p=list(map(int, input().split()))
for i in range(n):
    k=list(map(int, input().split()))
    arr1.append(k)
for i in range(m):
    l=list(map(int, input().split()))
    arr2.append(l)

print(np.concatenate((arr1,arr2),axis=0))
    

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Dot and Cross

In [3]:
import numpy as np
arr1=[]
arr2=[]
n=int(input())
for i in range(n):
    k=list(map(int, input().split()))
    arr1.append(k)
for i in range(n):
    l=list(map(int, input().split()))
    arr2.append(l)
np.dot(arr1,arr2)

2
1 2
3 4
1 2
3 4


array([[ 7, 10],
       [15, 22]])

### Inner and Outer



In [5]:
a=list(map(int, input().split()))
b=list(map(int, input().split()))
print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


### Min and Max

In [12]:
arr=[]
n,m=list(map(int, input().split()))
for i in range(n):
    k=list(map(int, input().split()))
    arr.append(k)
q=np.min(arr,axis=1)
print(max(q))

4 2
1 2
3 4
5 6
7 8
7


### Sum and Prod



In [15]:
arr=[]
n,m=list(map(int, input().split()))
for i in range(n):
    k=list(map(int, input().split()))
    arr.append(k)
q=np.sum(arr,axis=0)
print(np.prod(q))


4 2
1 2
3 4
5 6
7 8
320


### Transpose and Flatten

In [21]:
arr=[]
n,m=list(map(int, input().split()))
for i in range(n):
    k=list(map(int, input().split()))
    arr.append(k)
t=np.array(arr)
print(np.transpose(arr))
print(t.flatten())

4 2
1 2
3 4
5 6
7 8
[[1 3 5 7]
 [2 4 6 8]]
[1 2 3 4 5 6 7 8]


### Arrays



In [25]:
import numpy as np

def arrays(arr):
    k=arr[::-1]
    return np.array(k,float)
    
    
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)


1 2 3 4
[4. 3. 2. 1.]


### Floor, Ceil and Rint

In [49]:
import  numpy as np
np.set_printoptions(legacy='1.13')
a= list(map(float, input().split()))
k=np.array(a)
print(np.floor(k))
print(np.ceil(k))
print(np.rint(k))


1.1 2.7 3.2 6
[ 1.  2.  3.  6.]
[ 2.  3.  4.  6.]
[ 1.  3.  3.  6.]


### Array Mathematics



In [11]:
import numpy as np
a=[]
b=[]
n,m=list(map(int, input().split()))
for i in range(n):
    k=list(map(int, input().split()))
    a.append(k)
for i in range(n):
    q=list(map(int, input().split()))
    b.append(q)
arr1=np.array(a)
arr2=np.array(b)

print (arr1 + arr2) 
print (arr1 - arr2) 
print (arr1 * arr2) 
print (arr1//arr2) 
print (arr1%arr2)
print(arr1**arr2)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]



### Eye and Identity

In [12]:
a=[]
r,c=list(map(int,input().split()))
for i in range(r):
    k=list(map(int, input().split()))
    a.append(k)

    

3 3
1 2 3
4 5 6
7 8 9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [24]:
np.set_printoptions(legacy='1.13')
r,c=list(map(int,input().split()))
k=np.identity(r)
print(np.array(k))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Mean, Var, and Std

In [13]:
import numpy as np
np.set_printoptions(legacy='1.13')
arr=[]
n,m=list(map(int,input().split()))
for i in range(n):
    k=list(map(int,input().split()))
    arr.append(k)
print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(np.std(arr))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875



### Linear Algebra

In [26]:
arr=[]
n=int(input())
for i in range(n):
    k=list(map(float,input().split()))
    arr.append(k)
r=np.linalg.det(arr)
print(round(r,2))

2
1 2
3 4
-2.0
